# Generated by Django 5.1.6 on 2025-03-07 01:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_remove_machine_billing_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('working_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('working_end_time', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.technician')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workorder')),
            ],
        ),
    ]
