# Generated by Django 5.1.6 on 2025-03-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_workorder_customer_preferred_dates_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='skills',
            field=models.CharField(help_text="Comma-separated list of skills (e.g., 'service,installation')", max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='working_end_time',
            field=models.TimeField(default='16:00', help_text='End of working hours (e.g., 17:00 for 5 PM)'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='working_start_time',
            field=models.TimeField(default='08:00', help_text='Start of working hours (e.g., 10:00 for 10 AM)'),
        ),
        migrations.AlterField(
            model_name='workorderassignment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.technician'),
        ),
        migrations.AlterField(
            model_name='workorderassignment',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.workorder'),
        ),
        migrations.AlterModelTable(
            name='technician',
            table='technicians',
        ),
        migrations.AlterModelTable(
            name='workorderassignment',
            table='work_order_assignments',
        ),
    ]
