# Generated by Django 5.1.6 on 2025-04-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_workorder_customer_preferred_dates_and_more'),
        ('scheduling', '0002_alter_technician_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('travel_to_next', models.FloatField(default=5)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.technician')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workorder')),
            ],
            options={
                'db_table': 'schedule_entries',
            },
        ),
    ]
