# Generated by Django 5.1.6 on 2025-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='home_address',
            field=models.CharField(blank=True, default='Unknown Address', max_length=200),
        ),
    ]
