# Generated by Django 5.1.6 on 2025-04-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_technician_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='work_days',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
