# Generated by Django 5.2.12 on 2026-03-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_migrate_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPICallUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_api_call_usage',
                'unique_together': {('service', 'day')},
            },
        ),
    ]
