# Generated by Django 5.1.6 on 2025-02-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('total_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('lease_id', models.AutoField(primary_key=True, serialize=False)),
                ('lease_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('total_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'db_table': 'leases',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('said_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('not installed', 'Not Installed'), ('in repair', 'In Repair')], max_length=20)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('automation_flag', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lease')),
            ],
            options={
                'db_table': 'machines',
            },
        ),
    ]
