# Generated by Django 5.1.6 on 2025-02-22 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tech_notes', models.TextField(blank=True, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lease')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
            options={
                'db_table': 'work_orders',
            },
        ),
    ]
