# Generated by Django 5.1.6 on 2025-02-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Stats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_stats',
            },
        ),
        migrations.CreateModel(
            name='Lease_History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lease')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workorder')),
            ],
            options={
                'db_table': 'lease_history',
            },
        ),
        migrations.CreateModel(
            name='Machine_History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('billing_amount_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workorder')),
            ],
            options={
                'db_table': 'machine_history',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lease')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
