# Generated by Django 5.1.6 on 2025-02-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_stats_lease_history_machine_history_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('seasonal', 'Seasonal')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='final_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='first_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('installed', 'Installed'), ('not_installed', 'Not Installed'), ('sold', 'Sold'), ('decommissioned', 'Decommissioned')], max_length=20),
        ),
    ]
