# Generated by Django 5.1.6 on 2025-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lease_billing_cycle_lease_final_billing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('installed', 'Installed'), ('not_ready', 'Not Ready'), ('ready', 'Ready'), ('sold', 'Sold'), ('decommissioned', 'Decommissioned')], max_length=20),
        ),
    ]
