# Generated by Django 5.1.6 on 2025-02-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_machine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lease')),
            ],
            options={
                'db_table': 'billing',
            },
        ),
    ]
