# Generated by Django 5.1.6 on 2025-02-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='customer_preferred_dates',
            field=models.TextField(blank=True, help_text="Customer's preferred dates and times for service", null=True),
        ),
    ]
