# Generated by Django 5.1.6 on 2025-02-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workorder_customer_preferred_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
