# Generated by Django 5.1.6 on 2025-03-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lease_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='billing_amount',
        ),
    ]
