# Generated by Django 5.1.6 on 2025-03-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_machine_billing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('installation', 'Installation')], max_length=50),
        ),
        migrations.AddField(
            model_name='workorder',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_availability',
            field=models.CharField(blank=True, help_text="Customer availability (e.g., '8am-2pm Mon, Wed')", max_length=200),
        ),
    ]
