# Generated by Django 5.1.6 on 2025-03-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workorder_activity_type_workorder_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='customer_preferred_dates',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='task_type',
        ),
    ]
