# Generated by Django 5.1.6 on 2025-04-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_workorder_customer_preferred_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('complete', 'Complete')], default='submitted', max_length=20),
        ),
    ]
