# Generated by Django 5.1.6 on 2025-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorder',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
