# Generated by Django 5.1.6 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_workorder_notes_workorder_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("PM", "PM"),
                    ("Service", "Service"),
                    ("Ice", "Ice"),
                    ("Installation", "Installation"),
                ],
                default="Service",
                max_length=50,
            ),
        ),
    ]
